server:
  name: ecommercehub_api
  port: 9090
  production: false
  trace: false

database:
  url: "postgresql://postgres:postgres@localhost:5433/api?sslmode=disable"

service:

jwt:
  access_token_secret: ${JWT_ACCESS_TOKEN_SECRET}
  access_token_expire: ${JWT_ACCESS_TOKEN_EXPIRE}
  refresh_token_secret: ${JWT_REFRESH_TOKEN_SECRET}
  refresh_token_expire: ${JWT_REFRESH_TOKEN_EXPIRE}

redis:
  addr: localhost:6379
