// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/merchant.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MerchantStatus int32

const (
	MerchantStatus_MERCHANT_STATUS_UNSPECIFIED MerchantStatus = 0
	MerchantStatus_MERCHANT_STATUS_PENDING     MerchantStatus = 1
	MerchantStatus_MERCHANT_STATUS_ACTIVE      MerchantStatus = 2
	MerchantStatus_MERCHANT_STATUS_SUSPENDED   MerchantStatus = 3
	MerchantStatus_MERCHANT_STATUS_CLOSED      MerchantStatus = 4
)

// Enum value maps for MerchantStatus.
var (
	MerchantStatus_name = map[int32]string{
		0: "MERCHANT_STATUS_UNSPECIFIED",
		1: "MERCHANT_STATUS_PENDING",
		2: "MERCHANT_STATUS_ACTIVE",
		3: "MERCHANT_STATUS_SUSPENDED",
		4: "MERCHANT_STATUS_CLOSED",
	}
	MerchantStatus_value = map[string]int32{
		"MERCHANT_STATUS_UNSPECIFIED": 0,
		"MERCHANT_STATUS_PENDING":     1,
		"MERCHANT_STATUS_ACTIVE":      2,
		"MERCHANT_STATUS_SUSPENDED":   3,
		"MERCHANT_STATUS_CLOSED":      4,
	}
)

func (x MerchantStatus) Enum() *MerchantStatus {
	p := new(MerchantStatus)
	*p = x
	return p
}

func (x MerchantStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MerchantStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_merchant_proto_enumTypes[0].Descriptor()
}

func (MerchantStatus) Type() protoreflect.EnumType {
	return &file_proto_merchant_proto_enumTypes[0]
}

func (x MerchantStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MerchantStatus.Descriptor instead.
func (MerchantStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_merchant_proto_rawDescGZIP(), []int{0}
}

type Merchant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	LogoUrl       string                 `protobuf:"bytes,7,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	Status        MerchantStatus         `protobuf:"varint,8,opt,name=status,proto3,enum=merchant.MerchantStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Merchant) Reset() {
	*x = Merchant{}
	mi := &file_proto_merchant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Merchant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Merchant) ProtoMessage() {}

func (x *Merchant) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merchant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Merchant.ProtoReflect.Descriptor instead.
func (*Merchant) Descriptor() ([]byte, []int) {
	return file_proto_merchant_proto_rawDescGZIP(), []int{0}
}

func (x *Merchant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Merchant) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Merchant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Merchant) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Merchant) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Merchant) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Merchant) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *Merchant) GetStatus() MerchantStatus {
	if x != nil {
		return x.Status
	}
	return MerchantStatus_MERCHANT_STATUS_UNSPECIFIED
}

func (x *Merchant) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Merchant) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateMerchantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Description   *string                `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	LogoUrl       *string                `protobuf:"bytes,6,opt,name=logo_url,json=logoUrl,proto3,oneof" json:"logo_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMerchantRequest) Reset() {
	*x = CreateMerchantRequest{}
	mi := &file_proto_merchant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMerchantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMerchantRequest) ProtoMessage() {}

func (x *CreateMerchantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merchant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMerchantRequest.ProtoReflect.Descriptor instead.
func (*CreateMerchantRequest) Descriptor() ([]byte, []int) {
	return file_proto_merchant_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMerchantRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *CreateMerchantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateMerchantRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateMerchantRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateMerchantRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateMerchantRequest) GetLogoUrl() string {
	if x != nil && x.LogoUrl != nil {
		return *x.LogoUrl
	}
	return ""
}

type CreateMerchantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Merchant      *Merchant              `protobuf:"bytes,1,opt,name=merchant,proto3" json:"merchant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMerchantResponse) Reset() {
	*x = CreateMerchantResponse{}
	mi := &file_proto_merchant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMerchantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMerchantResponse) ProtoMessage() {}

func (x *CreateMerchantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merchant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMerchantResponse.ProtoReflect.Descriptor instead.
func (*CreateMerchantResponse) Descriptor() ([]byte, []int) {
	return file_proto_merchant_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMerchantResponse) GetMerchant() *Merchant {
	if x != nil {
		return x.Merchant
	}
	return nil
}

type GetMerchantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantRequest) Reset() {
	*x = GetMerchantRequest{}
	mi := &file_proto_merchant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantRequest) ProtoMessage() {}

func (x *GetMerchantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merchant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantRequest.ProtoReflect.Descriptor instead.
func (*GetMerchantRequest) Descriptor() ([]byte, []int) {
	return file_proto_merchant_proto_rawDescGZIP(), []int{3}
}

func (x *GetMerchantRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMerchantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Merchant      *Merchant              `protobuf:"bytes,1,opt,name=merchant,proto3" json:"merchant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantResponse) Reset() {
	*x = GetMerchantResponse{}
	mi := &file_proto_merchant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantResponse) ProtoMessage() {}

func (x *GetMerchantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merchant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantResponse.ProtoReflect.Descriptor instead.
func (*GetMerchantResponse) Descriptor() ([]byte, []int) {
	return file_proto_merchant_proto_rawDescGZIP(), []int{4}
}

func (x *GetMerchantResponse) GetMerchant() *Merchant {
	if x != nil {
		return x.Merchant
	}
	return nil
}

type GetMerchantByOwnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantByOwnerRequest) Reset() {
	*x = GetMerchantByOwnerRequest{}
	mi := &file_proto_merchant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantByOwnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantByOwnerRequest) ProtoMessage() {}

func (x *GetMerchantByOwnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merchant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantByOwnerRequest.ProtoReflect.Descriptor instead.
func (*GetMerchantByOwnerRequest) Descriptor() ([]byte, []int) {
	return file_proto_merchant_proto_rawDescGZIP(), []int{5}
}

func (x *GetMerchantByOwnerRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type GetMerchantByOwnerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Merchant      *Merchant              `protobuf:"bytes,1,opt,name=merchant,proto3" json:"merchant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantByOwnerResponse) Reset() {
	*x = GetMerchantByOwnerResponse{}
	mi := &file_proto_merchant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantByOwnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantByOwnerResponse) ProtoMessage() {}

func (x *GetMerchantByOwnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merchant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantByOwnerResponse.ProtoReflect.Descriptor instead.
func (*GetMerchantByOwnerResponse) Descriptor() ([]byte, []int) {
	return file_proto_merchant_proto_rawDescGZIP(), []int{6}
}

func (x *GetMerchantByOwnerResponse) GetMerchant() *Merchant {
	if x != nil {
		return x.Merchant
	}
	return nil
}

type UpdateMerchantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Email         *string                `protobuf:"bytes,3,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Phone         *string                `protobuf:"bytes,4,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	Description   *string                `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	LogoUrl       *string                `protobuf:"bytes,6,opt,name=logo_url,json=logoUrl,proto3,oneof" json:"logo_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMerchantRequest) Reset() {
	*x = UpdateMerchantRequest{}
	mi := &file_proto_merchant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMerchantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMerchantRequest) ProtoMessage() {}

func (x *UpdateMerchantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merchant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMerchantRequest.ProtoReflect.Descriptor instead.
func (*UpdateMerchantRequest) Descriptor() ([]byte, []int) {
	return file_proto_merchant_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateMerchantRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMerchantRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateMerchantRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *UpdateMerchantRequest) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *UpdateMerchantRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateMerchantRequest) GetLogoUrl() string {
	if x != nil && x.LogoUrl != nil {
		return *x.LogoUrl
	}
	return ""
}

type UpdateMerchantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Merchant      *Merchant              `protobuf:"bytes,1,opt,name=merchant,proto3" json:"merchant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMerchantResponse) Reset() {
	*x = UpdateMerchantResponse{}
	mi := &file_proto_merchant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMerchantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMerchantResponse) ProtoMessage() {}

func (x *UpdateMerchantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merchant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMerchantResponse.ProtoReflect.Descriptor instead.
func (*UpdateMerchantResponse) Descriptor() ([]byte, []int) {
	return file_proto_merchant_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateMerchantResponse) GetMerchant() *Merchant {
	if x != nil {
		return x.Merchant
	}
	return nil
}

type ListMerchantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *int32                 `protobuf:"varint,1,opt,name=page,proto3,oneof" json:"page,omitempty"`
	Limit         *int32                 `protobuf:"varint,2,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Search        *string                `protobuf:"bytes,3,opt,name=search,proto3,oneof" json:"search,omitempty"`
	Status        *MerchantStatus        `protobuf:"varint,4,opt,name=status,proto3,enum=merchant.MerchantStatus,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMerchantsRequest) Reset() {
	*x = ListMerchantsRequest{}
	mi := &file_proto_merchant_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMerchantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMerchantsRequest) ProtoMessage() {}

func (x *ListMerchantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merchant_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMerchantsRequest.ProtoReflect.Descriptor instead.
func (*ListMerchantsRequest) Descriptor() ([]byte, []int) {
	return file_proto_merchant_proto_rawDescGZIP(), []int{9}
}

func (x *ListMerchantsRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *ListMerchantsRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *ListMerchantsRequest) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

func (x *ListMerchantsRequest) GetStatus() MerchantStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return MerchantStatus_MERCHANT_STATUS_UNSPECIFIED
}

type ListMerchantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Merchants     []*Merchant            `protobuf:"bytes,1,rep,name=merchants,proto3" json:"merchants,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMerchantsResponse) Reset() {
	*x = ListMerchantsResponse{}
	mi := &file_proto_merchant_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMerchantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMerchantsResponse) ProtoMessage() {}

func (x *ListMerchantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merchant_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMerchantsResponse.ProtoReflect.Descriptor instead.
func (*ListMerchantsResponse) Descriptor() ([]byte, []int) {
	return file_proto_merchant_proto_rawDescGZIP(), []int{10}
}

func (x *ListMerchantsResponse) GetMerchants() []*Merchant {
	if x != nil {
		return x.Merchants
	}
	return nil
}

func (x *ListMerchantsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DeleteMerchantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMerchantRequest) Reset() {
	*x = DeleteMerchantRequest{}
	mi := &file_proto_merchant_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMerchantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMerchantRequest) ProtoMessage() {}

func (x *DeleteMerchantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merchant_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMerchantRequest.ProtoReflect.Descriptor instead.
func (*DeleteMerchantRequest) Descriptor() ([]byte, []int) {
	return file_proto_merchant_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteMerchantRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteMerchantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMerchantResponse) Reset() {
	*x = DeleteMerchantResponse{}
	mi := &file_proto_merchant_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMerchantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMerchantResponse) ProtoMessage() {}

func (x *DeleteMerchantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merchant_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMerchantResponse.ProtoReflect.Descriptor instead.
func (*DeleteMerchantResponse) Descriptor() ([]byte, []int) {
	return file_proto_merchant_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteMerchantResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_merchant_proto protoreflect.FileDescriptor

const file_proto_merchant_proto_rawDesc = "" +
	"\n" +
	"\x14proto/merchant.proto\x12\bmerchant\x1a\x1fgoogle/protobuf/timestamp.proto\"\xda\x02\n" +
	"\bMerchant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x19\n" +
	"\blogo_url\x18\a \x01(\tR\alogoUrl\x120\n" +
	"\x06status\x18\b \x01(\x0e2\x18.merchant.MerchantStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xd6\x01\n" +
	"\x15CreateMerchantRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1e\n" +
	"\blogo_url\x18\x06 \x01(\tH\x01R\alogoUrl\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_logo_url\"H\n" +
	"\x16CreateMerchantResponse\x12.\n" +
	"\bmerchant\x18\x01 \x01(\v2\x12.merchant.MerchantR\bmerchant\"$\n" +
	"\x12GetMerchantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"E\n" +
	"\x13GetMerchantResponse\x12.\n" +
	"\bmerchant\x18\x01 \x01(\v2\x12.merchant.MerchantR\bmerchant\"6\n" +
	"\x19GetMerchantByOwnerRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\"L\n" +
	"\x1aGetMerchantByOwnerResponse\x12.\n" +
	"\bmerchant\x18\x01 \x01(\v2\x12.merchant.MerchantR\bmerchant\"\xf7\x01\n" +
	"\x15UpdateMerchantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x03 \x01(\tH\x01R\x05email\x88\x01\x01\x12\x19\n" +
	"\x05phone\x18\x04 \x01(\tH\x02R\x05phone\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x03R\vdescription\x88\x01\x01\x12\x1e\n" +
	"\blogo_url\x18\x06 \x01(\tH\x04R\alogoUrl\x88\x01\x01B\a\n" +
	"\x05_nameB\b\n" +
	"\x06_emailB\b\n" +
	"\x06_phoneB\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_logo_url\"H\n" +
	"\x16UpdateMerchantResponse\x12.\n" +
	"\bmerchant\x18\x01 \x01(\v2\x12.merchant.MerchantR\bmerchant\"\xc7\x01\n" +
	"\x14ListMerchantsRequest\x12\x17\n" +
	"\x04page\x18\x01 \x01(\x05H\x00R\x04page\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x02 \x01(\x05H\x01R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06search\x18\x03 \x01(\tH\x02R\x06search\x88\x01\x01\x125\n" +
	"\x06status\x18\x04 \x01(\x0e2\x18.merchant.MerchantStatusH\x03R\x06status\x88\x01\x01B\a\n" +
	"\x05_pageB\b\n" +
	"\x06_limitB\t\n" +
	"\a_searchB\t\n" +
	"\a_status\"_\n" +
	"\x15ListMerchantsResponse\x120\n" +
	"\tmerchants\x18\x01 \x03(\v2\x12.merchant.MerchantR\tmerchants\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"'\n" +
	"\x15DeleteMerchantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"2\n" +
	"\x16DeleteMerchantResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*\xa5\x01\n" +
	"\x0eMerchantStatus\x12\x1f\n" +
	"\x1bMERCHANT_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17MERCHANT_STATUS_PENDING\x10\x01\x12\x1a\n" +
	"\x16MERCHANT_STATUS_ACTIVE\x10\x02\x12\x1d\n" +
	"\x19MERCHANT_STATUS_SUSPENDED\x10\x03\x12\x1a\n" +
	"\x16MERCHANT_STATUS_CLOSED\x10\x042\x8f\x04\n" +
	"\x0fMerchantService\x12S\n" +
	"\x0eCreateMerchant\x12\x1f.merchant.CreateMerchantRequest\x1a .merchant.CreateMerchantResponse\x12J\n" +
	"\vGetMerchant\x12\x1c.merchant.GetMerchantRequest\x1a\x1d.merchant.GetMerchantResponse\x12_\n" +
	"\x12GetMerchantByOwner\x12#.merchant.GetMerchantByOwnerRequest\x1a$.merchant.GetMerchantByOwnerResponse\x12S\n" +
	"\x0eUpdateMerchant\x12\x1f.merchant.UpdateMerchantRequest\x1a .merchant.UpdateMerchantResponse\x12P\n" +
	"\rListMerchants\x12\x1e.merchant.ListMerchantsRequest\x1a\x1f.merchant.ListMerchantsResponse\x12S\n" +
	"\x0eDeleteMerchant\x12\x1f.merchant.DeleteMerchantRequest\x1a .merchant.DeleteMerchantResponseB/Z-gitlab.com/ecommercehub1/merchant/proto;protob\x06proto3"

var (
	file_proto_merchant_proto_rawDescOnce sync.Once
	file_proto_merchant_proto_rawDescData []byte
)

func file_proto_merchant_proto_rawDescGZIP() []byte {
	file_proto_merchant_proto_rawDescOnce.Do(func() {
		file_proto_merchant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_merchant_proto_rawDesc), len(file_proto_merchant_proto_rawDesc)))
	})
	return file_proto_merchant_proto_rawDescData
}

var file_proto_merchant_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_merchant_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_merchant_proto_goTypes = []any{
	(MerchantStatus)(0),                // 0: merchant.MerchantStatus
	(*Merchant)(nil),                   // 1: merchant.Merchant
	(*CreateMerchantRequest)(nil),      // 2: merchant.CreateMerchantRequest
	(*CreateMerchantResponse)(nil),     // 3: merchant.CreateMerchantResponse
	(*GetMerchantRequest)(nil),         // 4: merchant.GetMerchantRequest
	(*GetMerchantResponse)(nil),        // 5: merchant.GetMerchantResponse
	(*GetMerchantByOwnerRequest)(nil),  // 6: merchant.GetMerchantByOwnerRequest
	(*GetMerchantByOwnerResponse)(nil), // 7: merchant.GetMerchantByOwnerResponse
	(*UpdateMerchantRequest)(nil),      // 8: merchant.UpdateMerchantRequest
	(*UpdateMerchantResponse)(nil),     // 9: merchant.UpdateMerchantResponse
	(*ListMerchantsRequest)(nil),       // 10: merchant.ListMerchantsRequest
	(*ListMerchantsResponse)(nil),      // 11: merchant.ListMerchantsResponse
	(*DeleteMerchantRequest)(nil),      // 12: merchant.DeleteMerchantRequest
	(*DeleteMerchantResponse)(nil),     // 13: merchant.DeleteMerchantResponse
	(*timestamppb.Timestamp)(nil),      // 14: google.protobuf.Timestamp
}
var file_proto_merchant_proto_depIdxs = []int32{
	0,  // 0: merchant.Merchant.status:type_name -> merchant.MerchantStatus
	14, // 1: merchant.Merchant.created_at:type_name -> google.protobuf.Timestamp
	14, // 2: merchant.Merchant.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 3: merchant.CreateMerchantResponse.merchant:type_name -> merchant.Merchant
	1,  // 4: merchant.GetMerchantResponse.merchant:type_name -> merchant.Merchant
	1,  // 5: merchant.GetMerchantByOwnerResponse.merchant:type_name -> merchant.Merchant
	1,  // 6: merchant.UpdateMerchantResponse.merchant:type_name -> merchant.Merchant
	0,  // 7: merchant.ListMerchantsRequest.status:type_name -> merchant.MerchantStatus
	1,  // 8: merchant.ListMerchantsResponse.merchants:type_name -> merchant.Merchant
	2,  // 9: merchant.MerchantService.CreateMerchant:input_type -> merchant.CreateMerchantRequest
	4,  // 10: merchant.MerchantService.GetMerchant:input_type -> merchant.GetMerchantRequest
	6,  // 11: merchant.MerchantService.GetMerchantByOwner:input_type -> merchant.GetMerchantByOwnerRequest
	8,  // 12: merchant.MerchantService.UpdateMerchant:input_type -> merchant.UpdateMerchantRequest
	10, // 13: merchant.MerchantService.ListMerchants:input_type -> merchant.ListMerchantsRequest
	12, // 14: merchant.MerchantService.DeleteMerchant:input_type -> merchant.DeleteMerchantRequest
	3,  // 15: merchant.MerchantService.CreateMerchant:output_type -> merchant.CreateMerchantResponse
	5,  // 16: merchant.MerchantService.GetMerchant:output_type -> merchant.GetMerchantResponse
	7,  // 17: merchant.MerchantService.GetMerchantByOwner:output_type -> merchant.GetMerchantByOwnerResponse
	9,  // 18: merchant.MerchantService.UpdateMerchant:output_type -> merchant.UpdateMerchantResponse
	11, // 19: merchant.MerchantService.ListMerchants:output_type -> merchant.ListMerchantsResponse
	13, // 20: merchant.MerchantService.DeleteMerchant:output_type -> merchant.DeleteMerchantResponse
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_merchant_proto_init() }
func file_proto_merchant_proto_init() {
	if File_proto_merchant_proto != nil {
		return
	}
	file_proto_merchant_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_merchant_proto_msgTypes[7].OneofWrappers = []any{}
	file_proto_merchant_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_merchant_proto_rawDesc), len(file_proto_merchant_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_merchant_proto_goTypes,
		DependencyIndexes: file_proto_merchant_proto_depIdxs,
		EnumInfos:         file_proto_merchant_proto_enumTypes,
		MessageInfos:      file_proto_merchant_proto_msgTypes,
	}.Build()
	File_proto_merchant_proto = out.File
	file_proto_merchant_proto_goTypes = nil
	file_proto_merchant_proto_depIdxs = nil
}
