basePath: /api/v1
definitions:
  gitlab_com_ecommercehub1_api_internal_present_http_dto.LoginRequest:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
  gitlab_com_ecommercehub1_api_internal_present_http_dto.LoginResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
      session_id:
        type: integer
      user_id:
        type: string
    type: object
  gitlab_com_ecommercehub1_api_internal_present_http_dto.LogoutRequest:
    properties:
      session_id:
        type: integer
    required:
    - session_id
    type: object
  gitlab_com_ecommercehub1_api_internal_present_http_dto.RefreshTokenRequest:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  gitlab_com_ecommercehub1_api_internal_present_http_dto.RefreshTokenResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  gitlab_com_ecommercehub1_api_internal_present_http_dto.RegisterRequest:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
  gitlab_com_ecommercehub1_api_internal_present_http_dto.RegisterResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
      session_id:
        type: integer
      user_id:
        type: string
    type: object
host: localhost:9090
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: API documentation for CommerceHub backend service.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: CommerceHub API
  version: "1.0"
paths:
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      description: Authenticate user with email and password
      parameters:
      - description: Login credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/gitlab_com_ecommercehub1_api_internal_present_http_dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gitlab_com_ecommercehub1_api_internal_present_http_dto.LoginResponse'
      summary: Login user
      tags:
      - Auth
  /api/v1/auth/logout:
    post:
      consumes:
      - application/json
      description: Revoke the user's current session
      parameters:
      - description: Logout request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/gitlab_com_ecommercehub1_api_internal_present_http_dto.LogoutRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Logout user
      tags:
      - Auth
  /api/v1/auth/refresh:
    post:
      consumes:
      - application/json
      description: Get a new access token using a refresh token
      parameters:
      - description: Refresh token
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/gitlab_com_ecommercehub1_api_internal_present_http_dto.RefreshTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gitlab_com_ecommercehub1_api_internal_present_http_dto.RefreshTokenResponse'
      summary: Refresh access token
      tags:
      - Auth
  /api/v1/auth/register:
    post:
      consumes:
      - application/json
      description: Register a new user with email and password
      parameters:
      - description: Register credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/gitlab_com_ecommercehub1_api_internal_present_http_dto.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gitlab_com_ecommercehub1_api_internal_present_http_dto.RegisterResponse'
      summary: Register user
      tags:
      - Auth
  /health:
    get:
      consumes:
      - application/json
      description: Check the health of the application and its dependencies
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Health Check
      tags:
      - System
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
