services:
  redisinsight:
    image: redis/redisinsight:3.2
    container_name: ecommerce_redisinsight
    restart: always
    ports:
      - "5540:5540"
    networks:
      - hexta_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  hexta_network:
    external: true

